//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://spxflow.com/products/XMLSchema")]
[System.Xml.Serialization.XmlRootAttribute("brand", Namespace="http://spxflow.com/products/XMLSchema", IsNullable=false)]
public enum brandName {
    
    /// <remarks/>
    APV,
    
    /// <remarks/>
    Airpel,
    
    /// <remarks/>
    PowerTeam,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spxflow.com/products/XMLSchema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://spxflow.com/products/XMLSchema", IsNullable=false)]
public partial class review {
    
    private string ratingField;
    
    private string commentField;
    
    private string userField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    public string user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spxflow.com/products/XMLSchema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://spxflow.com/products/XMLSchema", IsNullable=false)]
public partial class reviews {
    
    private review[] reviewField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("review")]
    public review[] review {
        get {
            return this.reviewField;
        }
        set {
            this.reviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spxflow.com/products/XMLSchema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://spxflow.com/products/XMLSchema", IsNullable=false)]
public partial class product {
    
    private long idField;
    
    private string titleField;
    
    private string shortDescriptionField;
    
    private brandName brandField;
    
    private review[] reviewsField;
    
    private System.DateTime datePublishedField;
    
    private bool datePublishedFieldSpecified;
    
    /// <remarks/>
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string shortDescription {
        get {
            return this.shortDescriptionField;
        }
        set {
            this.shortDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public brandName brand {
        get {
            return this.brandField;
        }
        set {
            this.brandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("review", IsNullable=false)]
    public review[] reviews {
        get {
            return this.reviewsField;
        }
        set {
            this.reviewsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public System.DateTime datePublished {
        get {
            return this.datePublishedField;
        }
        set {
            this.datePublishedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool datePublishedSpecified {
        get {
            return this.datePublishedFieldSpecified;
        }
        set {
            this.datePublishedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spxflow.com/products/XMLSchema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://spxflow.com/products/XMLSchema", IsNullable=false)]
public partial class products {
    
    private product[] productField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("product")]
    public product[] product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
}
